# Generated by Django 4.1.7 on 2023-04-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_appuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='cover_photo',
            field=models.ImageField(null=True, upload_to='cover_photos'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_pictures'),
        ),
    ]
