# Generated by Django 4.1.7 on 2023-05-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_friending_friend_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='friending',
            name='sent',
            field=models.BigIntegerField(
                default=4, verbose_name='request_sent_user'),
            preserve_default=False,
        ),
    ]
