# Generated by Django 4.1.7 on 2023-05-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_appuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_picture',
            field=models.ImageField(
                default='media/profile_pictures/default-profile-picture_xdklkn.jpg', upload_to='profile_pictures'),
        ),
    ]
