# Generated by Django 4.1.7 on 2023-05-01 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.BigIntegerField(verbose_name='request_sent_user')),
                ('state', models.CharField(choices=[('PE', 'Pending'), ('FR', 'Friended')], default='PE', max_length=2)),
                ('friend_datetime', models.DateTimeField(default=None, null=True, verbose_name='datetime friended')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_friending', to=settings.AUTH_USER_MODEL)),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_friending', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='friending',
            index=models.Index(fields=['first', 'second'], name='friending_f_first_i_24078d_idx'),
        ),
        migrations.AddConstraint(
            model_name='friending',
            constraint=models.UniqueConstraint(fields=('first', 'second'), name='friend_request'),
        ),
    ]
