# Generated by Django 4.1.7 on 2023-04-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appuser',
            table=None,
        ),
    ]
