# Generated by Django 4.1.7 on 2023-04-30 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_alter_appuser_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PE', 'Pending'), ('FR', 'Friended')], default='PE', max_length=2)),
                ('friend_datetime', models.DateTimeField(default=None, verbose_name='datetime friended')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_friending', to=settings.AUTH_USER_MODEL)),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_friending', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='friending',
            index=models.Index(fields=['first', 'second'], name='custom_auth_first_i_2e824f_idx'),
        ),
        migrations.AddConstraint(
            model_name='friending',
            constraint=models.UniqueConstraint(fields=('first', 'second'), name='friend_request'),
        ),
    ]
