# Generated by Django 4.1.7 on 2023-05-01 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_friending_sent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friending',
        ),
    ]
